### PR TITLE
Fixes ISS #96 - Allows versioning to be turned off and still works

### PR DESCRIPTION
**Pull request by mholck**
Allows versioning to be turned off and still works without the libraries needing to be named with the version number in them

### CODE REVIEW

**Comment by JPercival** [comment]
I tested the RefreshIG operation on cqframework/ecqm-content-r4 without the -v and dbcg/connectathon/fhir401 with -v

For ecqm-content-r4 I had to update the _refresh scripts to be compatible with this branch of the cqf-tooling. When I ran the tooling I got:

```
11:07:54.244 [main] WARN o.o.cqf.tooling.utilities.LogUtils - EXM124v8 could not be processed:
Resource could not be processed: EXM124v8
5 included cql Libraries not found:
FHIRHelpers-4.0.0 MISSING
Hospice-1.0.000 MISSING
AdultOutpatientEncounters-1.1.000 MISSING
MATGlobalCommonFunctions-4.0.000 MISSING
SupplementalDataElements-1.0.0 MISSING
Resource could not be processed: EXM124v8
/home/jp/repos/ecqm-content-r4/input/resources/library/home/jp/repos/ecqm-content-r4/input/resources/library-FHIR-ModelInfo-4.0.0.json (No such file or directory)
11:07:54.245 [main] WARN o.o.cqf.tooling.utilities.LogUtils -
0 Measures successfully bundled:
1 Measures refreshed, but not bundled (due to issues):
EXM124v8 REFRESHED
```
Note this missing /Library/ directory of the filepath, and the additional library- prefix of the resource name, and the version attached to the filename. 

```input/resources/library-FHIR-ModelInfo-4.0.0.json```

The resources themselves had urls and references without versions in the Id, which looks right to me.


On DBCG dbcg/connectathon/fhir401 I had numerous warnings that were similar:
```
Resource could not be processed: MATGlobalCommonFunctions-5.0.000                  /home/jp/repos/connectathon/fhir401/input/resources/Library/home/jp/repos/connectathon/fhir401/input/resources/Library-MATGlobalCommonFunctions-5.0.000.json (No such file or directory)
```
These are also missing the /Library/ directory, and the resource still has Library- prefix.

The resources themselves look correct to me.

**Comment by mholck** [comment]
How are you testing this then? I just have the code opened in my IDE (Eclipse) and run it using -RefreshIG -ini="/Users/mholck/Development/CQF_Ruler/connectathon/fhir401/ig.ini" -t -d -p -v and all 15 measures bundle fine in connectathon fhir401
and run it with -RefreshIG -ini="/Users/mholck/Development/ecqm-content-r4/ig.ini" -t -d -p
and the EXM124v8 bundles fine

**Comment by JPercival** [comment]
@mholck and I jumped on a video chat and chased it down to a case-sensitivity issue. My machine (Ubuntu 20.10) is case sensitive while mholk's (MacOS) is not. mholck is investigating options.

**Review by JPercival — APPROVED** [review]
Tested locally, LGTM.

**Pull request merged**
