### PR TITLE
Add config file and remove ANC hard coding

### PR DESCRIPTION
**Pull request by delcroip**
- Use regex when ANC was hard coded
- Have a config.json file to avoid rebuilding the tool for each DAK

Next activity:
- structure the config.json
- add all the "bat/sh" script params in the config files
-  look for a approach to reuse the hand defined CQL

### CODE REVIEW

**Comment by delcroip** [comment]
covers #303

**Review by brynrhodes — CHANGES_REQUESTED** [review]
Overall the changes look good, but it looks like the fork is based on an older version, so the newer example generation logic is being removed. Is that intentional? I don't see anywhere that it's pulling it back in, so this feel like it just needs to be updated from the upstream repository?

**Comment by delcroip** [comment]
Thanks @brynrhodes  for the feedback,

We will work on early december 

br

**Comment by delcroip** [comment]
@brynrhodes  we have merged masted and I am starting a doc for the column to use

**Comment by JPercival** [comment]
Closed in favor of #493

**Pull request closed without merging**
