### PR TITLE
Only load xml and json files for processing

### PR DESCRIPTION
**Pull request by bryantaustin13**
Measure and Library Processors should only load xml and json files for processing, not all files in a directory.

**Description**
This fixes the error caused by trying to load all files in a directory for refresh processing. Instead it only loads .xml and .json files.

For measure and library processors only load .xml and .json files and then process those.

- Github Issue:  
- [ X] I've read the contribution guidelines 
- [ X] Code compiles without errors
- [ ] Tests are created / updated
- [ ] Documentation is created / updated

By creating this PR you acknowledge that your contribution will be licensed under Apache 2.0

### CODE REVIEW

**Comment by bryantaustin13** [comment]
Hold on this. After merging in master there is an error in DroolToElmVisitorIT where xv no longer exists in the engine.

**Comment by bryantaustin13** [comment]
This should be ready to go now.

**Review by mdnazmulkarim — APPROVED** [review]
Looks perfect!!

**Review by sliver007 — APPROVED** [review]
Looks good!

**Pull request merged**
